name: xarhani
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cloud_firestore: 4.17.5
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.8
  google_sign_in: ^6.1.6
  google_maps_flutter: ^2.3.0
  permission_handler: ^10.4.0
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/martita.jpg
    - assets/myra.jpg
    - assets/icon.png
    - assets/google_logo.png
