// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB91WlceaxoyKJQD83YZvEe1Hb5j0Kgyg8',
    appId: '1:794663120290:web:9ef4415b033f3493ed16fb',
    messagingSenderId: '794663120290',
    projectId: 'xarhani-99f05',
    authDomain: 'xarhani-99f05.firebaseapp.com',
    storageBucket: 'xarhani-99f05.firebasestorage.app',
    measurementId: 'G-CLZ7PKWBFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3uXu04X6d6uDCxz4gIVRw_JHCa_o0GtE',
    appId: '1:794663120290:android:8b5d331e4531aec1ed16fb',
    messagingSenderId: '794663120290',
    projectId: 'xarhani-99f05',
    storageBucket: 'xarhani-99f05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjBGDmee6wb9Y5IE8L_i2dNIK1c-8ubfE',
    appId: '1:794663120290:ios:cc0b7165799afca7ed16fb',
    messagingSenderId: '794663120290',
    projectId: 'xarhani-99f05',
    storageBucket: 'xarhani-99f05.firebasestorage.app',
    iosBundleId: 'com.example.xarhani',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjBGDmee6wb9Y5IE8L_i2dNIK1c-8ubfE',
    appId: '1:794663120290:ios:cc0b7165799afca7ed16fb',
    messagingSenderId: '794663120290',
    projectId: 'xarhani-99f05',
    storageBucket: 'xarhani-99f05.firebasestorage.app',
    iosBundleId: 'com.example.xarhani',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB91WlceaxoyKJQD83YZvEe1Hb5j0Kgyg8',
    appId: '1:794663120290:web:aa976da1b9b85ddaed16fb',
    messagingSenderId: '794663120290',
    projectId: 'xarhani-99f05',
    authDomain: 'xarhani-99f05.firebaseapp.com',
    storageBucket: 'xarhani-99f05.firebasestorage.app',
    measurementId: 'G-8H0VHLG8JF',
  );

}